### ISSUE TITLE
dir_name = './data/test/' + '%0.5d'%char_dict[tagcode_unicode]

### ISSUE THREAD

**Issue by River022** [orange90/HandWrittenChineseRecogntion#1]
Got error when debugging convert_data.py, can you please help out?  Thanks.

D:\DEV\Python\Envs\DLPy36\Scripts\python.exe "C:\Program Files (x86)\JetBrains\PyCharm 4.5.4\helpers\pydev\pydevd.py" --multiproc --client 127.0.0.1 --port 56353 --file D:/DEV/Python/CodeBase/hanzishibie/HandWrittenChineseRecogntion-master/convert_data.py
pydev debugger: process 11904 is connecting

Connected to pydev debugger (build 141.2569)
0
start extracting training data
start extracting testing data
Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm 4.5.4\helpers\pydev\pydevd.py", line 2358, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files (x86)\JetBrains\PyCharm 4.5.4\helpers\pydev\pydevd.py", line 1778, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files (x86)\JetBrains\PyCharm 4.5.4\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc) 
  File "D:/DEV/Python/CodeBase/hanzishibie/HandWrittenChineseRecogntion-master/convert_data.py", line 67, in <module>
    dir_name = './data/test/' + '%0.5d'%char_dict[tagcode_unicode]
KeyError: '啊'

Process finished with exit code -1

**Comment by River022** [comment]
Please ignore the issue report, just recognized that I should have unzipped the .alz file before run the python script.  Sorry for the spam.
